/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author pc
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuAlumnos = new javax.swing.JMenu();
        jmiAlumnos = new javax.swing.JMenuItem();
        jMenuMaterias = new javax.swing.JMenu();
        jmiMaterias = new javax.swing.JMenuItem();
        jMenuInscripcion = new javax.swing.JMenu();
        jmiItemInscripcion = new javax.swing.JMenuItem();
        jmiCargarNotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        JMenuAlumnos.setText("Alumno");

        jmiAlumnos.setText("Gestion Alumnos");
        jmiAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnosActionPerformed(evt);
            }
        });
        JMenuAlumnos.add(jmiAlumnos);

        jMenuBar1.add(JMenuAlumnos);

        jMenuMaterias.setText("Materias");

        jmiMaterias.setText("Gestion Materias");
        jmiMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMateriasActionPerformed(evt);
            }
        });
        jMenuMaterias.add(jmiMaterias);

        jMenuBar1.add(jMenuMaterias);

        jMenuInscripcion.setText("Inscripcion");
        jMenuInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInscripcionActionPerformed(evt);
            }
        });

        jmiItemInscripcion.setText("ListarInscripciones");
        jmiItemInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiItemInscripcionActionPerformed(evt);
            }
        });
        jMenuInscripcion.add(jmiItemInscripcion);

        jmiCargarNotas.setText("Cargar notas");
        jmiCargarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargarNotasActionPerformed(evt);
            }
        });
        jMenuInscripcion.add(jmiCargarNotas);

        jMenuBar1.add(jMenuInscripcion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumno cargarAlumnos = new VistaAlumno();
        cargarAlumnos.setVisible(true);
        escritorio.add(cargarAlumnos);
    }//GEN-LAST:event_jmiAlumnosActionPerformed

    private void jmiMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaMaterias cargarMaterias = new VistaMaterias();
        cargarMaterias.setVisible(true);
        escritorio.add(cargarMaterias);
    }//GEN-LAST:event_jmiMateriasActionPerformed

    private void jMenuInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaInscripcion cargarInscripcion = new VistaInscripcion();
        cargarInscripcion.setVisible(true);
        escritorio.add(cargarInscripcion);
    }//GEN-LAST:event_jMenuInscripcionActionPerformed

    private void jmiCargarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaCargaNotas cargaNotas = new VistaCargaNotas();
        cargaNotas.setVisible(true);
        escritorio.add(cargaNotas);
    }//GEN-LAST:event_jmiCargarNotasActionPerformed

    private void jmiItemInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiItemInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaListarInscripciones listarIns = new VistaListarInscripciones();
        listarIns.setVisible(true);
        escritorio.add(listarIns);
    }//GEN-LAST:event_jmiItemInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAlumnos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInscripcion;
    private javax.swing.JMenu jMenuMaterias;
    private javax.swing.JMenuItem jmiAlumnos;
    private javax.swing.JMenuItem jmiCargarNotas;
    private javax.swing.JMenuItem jmiItemInscripcion;
    private javax.swing.JMenuItem jmiMaterias;
    // End of variables declaration//GEN-END:variables
}
