/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Alumno;
import entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AlumnoData;
import persistencia.MateriaData;
import persistencia.MiConexion;

/**
 *
 * @author pc
 */
public class VistaMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMaterias
     */
    MiConexion conex = new MiConexion("jdbc:mariadb://localhost:3306/ulp2025gp9", "root", "");
    MateriaData materiaD = new MateriaData(conex);
    private DefaultTableModel modeloMaterias = new DefaultTableModel();
    public VistaMaterias() {
        initComponents();
        cargarCombo();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSeleccione = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jlIdAlumno = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfIdMateria = new javax.swing.JTextField();
        jtfAnio = new javax.swing.JTextField();
        cbMetodos = new javax.swing.JComboBox<>();
        jrbActivo = new javax.swing.JRadioButton();
        jrbInactivo = new javax.swing.JRadioButton();
        jbActualizar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbAlta_baja = new javax.swing.JButton();
        jbListar = new javax.swing.JButton();

        jlSeleccione.setText("Seleccione");

        jbLimpiar.setBackground(new java.awt.Color(0, 102, 0));
        jbLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jTableMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMateria);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setText("Complete los datos");

        jlDni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlDni.setText("Nombre");

        jlApellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlApellido.setText("Año");

        jlNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlNombre.setText("Estado");

        jbGuardar.setBackground(new java.awt.Color(0, 102, 0));
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setText("Cargar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jlIdAlumno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlIdAlumno.setText("idMateria ");

        jtfNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtfNombre.setEnabled(false);
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfIdMateria.setBackground(new java.awt.Color(255, 255, 255));
        jtfIdMateria.setEnabled(false);

        jtfAnio.setBackground(new java.awt.Color(255, 255, 255));
        jtfAnio.setEnabled(false);
        jtfAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnioActionPerformed(evt);
            }
        });

        cbMetodos.setBackground(new java.awt.Color(255, 255, 255));
        cbMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodosActionPerformed(evt);
            }
        });

        jrbActivo.setText("Activo");
        jrbActivo.setEnabled(false);
        jrbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbActivoActionPerformed(evt);
            }
        });

        jrbInactivo.setText("Inactivo");
        jrbInactivo.setEnabled(false);

        jbActualizar.setBackground(new java.awt.Color(0, 102, 0));
        jbActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBuscar.setBackground(new java.awt.Color(0, 102, 0));
        jbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbBuscar.setText("Buscar");

        jbEliminar.setBackground(new java.awt.Color(0, 102, 0));
        jbEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbEliminar.setText("Eliminar");

        jbAlta_baja.setBackground(new java.awt.Color(0, 102, 0));
        jbAlta_baja.setForeground(new java.awt.Color(255, 255, 255));
        jbAlta_baja.setText("Alta/Baja");

        jbListar.setBackground(new java.awt.Color(0, 102, 0));
        jbListar.setForeground(new java.awt.Color(255, 255, 255));
        jbListar.setText("Ver");
        jbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlSeleccione)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlIdAlumno)
                                    .addComponent(jlApellido))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfAnio)
                                    .addComponent(jtfIdMateria))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlDni)
                                    .addComponent(jlNombre))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jrbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jrbInactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNombre))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbAlta_baja)
                                .addGap(18, 18, 18)
                                .addComponent(jbListar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSeleccione)
                    .addComponent(cbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdAlumno)
                    .addComponent(jtfIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(jtfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre)
                    .addComponent(jrbActivo)
                    .addComponent(jrbInactivo))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbActualizar)
                    .addComponent(jbBuscar)
                    .addComponent(jbEliminar)
                    .addComponent(jbAlta_baja)
                    .addComponent(jbListar)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        jtfNombre.setText("");
        jtfAnio.setText("");
        jtfAnio.setText("");
        //solo funciona sin el boton de grupo
        jrbActivo.setSelected(false);
        jrbInactivo.setSelected(false);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        //Validacion de campos vacios
        if(jtfNombre.getText().trim().isEmpty() || jtfAnio.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios");
            return;
        }
        if(!jrbActivo.isSelected() || jrbInactivo.isSelected()) {
            JOptionPane.showMessageDialog(this, "No tiene estado alguno");
            return;
        }
        try {
            String nombre = jtfNombre.getText();
            int anio = Integer.parseInt(jtfAnio.getText());
            Boolean estado;
            if(jrbActivo.isSelected()){
                estado = true;
            }else{
                estado = false;
            }
            Materia materia = new Materia(nombre, anio, estado);
            if(materiaD.materiaNueva(materia)) {
                JOptionPane.showMessageDialog(this, "Materia guardada");
            }else{
                JOptionPane.showMessageDialog(this, "La materia ya existe");
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void cbMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodosActionPerformed
        //Dependiendo de que seleccione se activan y desactivan x campos
        String opciones = (String)cbMetodos.getSelectedItem();

        switch(opciones){
            case "Cargar Materia":
            jtfIdMateria.setEnabled(true);
            jtfNombre.setEnabled(true);
            jtfAnio.setEnabled(true);
            jrbActivo.setEnabled(true);
            jrbInactivo.setEnabled(true);
            jbActualizar.setEnabled(false);
            jbAlta_baja.setEnabled(false);
            jbBuscar.setEnabled(false);
            jbEliminar.setEnabled(false);
            jbGuardar.setEnabled(true);
            jbLimpiar.setEnabled(true);
            jbListar.setEnabled(false);
            
            break;
            
            case "Actualizar":
            jtfIdMateria.setEnabled(true);
            jtfNombre.setEnabled(true);
            jtfAnio.setEnabled(true);
            jrbActivo.setEnabled(true);
            jrbInactivo.setEnabled(true);
            jbActualizar.setEnabled(true);
            jbAlta_baja.setEnabled(false);
            jbBuscar.setEnabled(false);
            jbEliminar.setEnabled(false);
            jbGuardar.setEnabled(false);
            jbLimpiar.setEnabled(true);
            jbListar.setEnabled(false);
            
            break;
            
            case "Borrar":
            jtfIdMateria.setEnabled(true);
            jtfNombre.setEnabled(false);
            jtfAnio.setEnabled(false);
            jrbActivo.setEnabled(false);
            jrbInactivo.setEnabled(false);
            jbActualizar.setEnabled(false);
            jbAlta_baja.setEnabled(false);
            jbBuscar.setEnabled(false);
            jbEliminar.setEnabled(true);
            jbGuardar.setEnabled(false);
            jbLimpiar.setEnabled(true);
            jbListar.setEnabled(false);
            
            break;
            
            case "Baja / alta logica":
            jtfIdMateria.setEnabled(true);
            jtfNombre.setEnabled(false);
            jtfAnio.setEnabled(false);
            jrbActivo.setEnabled(true);
            jrbInactivo.setEnabled(true);
            jbActualizar.setEnabled(false);
            jbAlta_baja.setEnabled(true);
            jbBuscar.setEnabled(false);
            jbEliminar.setEnabled(false);
            jbGuardar.setEnabled(false);
            jbLimpiar.setEnabled(true);
            jbListar.setEnabled(false);
            
            break;
            
            case "Buscar":
            jtfIdMateria.setEnabled(true);
            jtfNombre.setEnabled(false);
            jtfAnio.setEnabled(false);
            jrbActivo.setEnabled(false);
            jrbInactivo.setEnabled(false);
            jbActualizar.setEnabled(false);
            jbAlta_baja.setEnabled(false);
            jbBuscar.setEnabled(true);
            jbEliminar.setEnabled(false);
            jbGuardar.setEnabled(false);
            jbLimpiar.setEnabled(true);
            jbListar.setEnabled(false);
            
            break;
            
            case "Listar":
            jtfIdMateria.setEnabled(false);
            jtfNombre.setEnabled(false);
            jtfAnio.setEnabled(false);
            jrbActivo.setEnabled(false);
            jrbInactivo.setEnabled(false);
            jbActualizar.setEnabled(false);
            jbAlta_baja.setEnabled(false);
            jbBuscar.setEnabled(false);
            jbEliminar.setEnabled(false);
            jbGuardar.setEnabled(false);
            jbLimpiar.setEnabled(true);
            jbListar.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_cbMetodosActionPerformed

    private void jtfAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnioActionPerformed

    private void jrbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbActivoActionPerformed

    private void jbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarActionPerformed
        ArrayList<Materia> listaDeMaterias = new ArrayList();
        materiaD.listarMaterias();
        for(Materia aux : listaDeMaterias){
            modeloMaterias.addRow(new Object [] {
                aux.getIdMateria(),
                aux.getNombre(),
                aux.getAnio(),
                aux.isEstado()
            });
        }
        
    }//GEN-LAST:event_jbListarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
       try {
            if (jtfIdMateria.getText().trim().isEmpty() || jtfNombre.getText().trim().isEmpty()
                    || jtfAnio.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se puedo realizar la actulizacion. Los campos no pueden estar vacios");
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Materia actualizado correctamente");
            }
            if (!jrbInactivo.isSelected()||jrbActivo.isSelected()) {
               JOptionPane.showMessageDialog(this, "No tiene estado alguno");
               return;
           }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error.");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    public void cargarCombo(){  
        cbMetodos.addItem("Cargar Materia");
        cbMetodos.addItem("Actualizar");
        cbMetodos.addItem("Borrar");
        cbMetodos.addItem("Baja / alta logica");
        cbMetodos.addItem("Buscar");
        cbMetodos.addItem("Listar");
    }

    private void armarCabecera(){
        modeloMaterias.addColumn("IdMateria");
        modeloMaterias.addColumn("Nombre");
        modeloMaterias.addColumn("Año");
        modeloMaterias.addColumn("Estado");
        jTableMateria.setModel(modeloMaterias);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMateria;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta_baja;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbListar;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlIdAlumno;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlSeleccione;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JRadioButton jrbInactivo;
    private javax.swing.JTextField jtfAnio;
    private javax.swing.JTextField jtfIdMateria;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
